<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menus = [
            ['nama_produk' => 'Ayam Bakar', 'kategori_id' => 1, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Goreng Rempah', 'kategori_id' => 1, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Kari', 'kategori_id' => 1, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Mangut', 'kategori_id' => 1, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Soto Ayam Laras', 'kategori_id' => 1, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Nasi Bebek Ireng', 'kategori_id' => 2, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Americano', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Aren', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Avocado Juice', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Blue Paradise', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Butterscotch', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Caffe Latte', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Caramel', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Chocolate Milk', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Dragon Fruit Juice', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Lemon Squash', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Lemon Tea', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Lychee Tea', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Matcha Milk', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Melon Juice', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - ORANGE JUICE', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Red Velvet Milk', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Strawberry Juice', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Strawberry Milk', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Summer Paradise', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Vanilla', 'kategori_id' => 3, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAFE - Calamari Rings', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Catfish Finger', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Cheesy Pizza', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Chicken Popcorn Teriyaki', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Fettuccine Creamy Chicken', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - French Fries', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Garden Pizza', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Lele Popcorn Sambal Jeruk', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - LGR Wings', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Nachos Garden', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Salted Chili Tofu', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'CAFE - Spaghetti Bolognaise', 'kategori_id' => 4, 'satuan' => 'Porsi'],
            ['nama_produk' => 'AMERICANO', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'BUTTERSCOTCH LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CAPPUCINO', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CARAMEL LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'COCONUT MILK LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'COFFE LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'GULA AREN LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'HAZELNUT LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'TUBRUK', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'VANILLA LATTE', 'kategori_id' => 5, 'satuan' => 'Gelas'],
            ['nama_produk' => 'Fruit Plate', 'kategori_id' => 6, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Pisang Goreng', 'kategori_id' => 6, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Roti Bakar', 'kategori_id' => 6, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Singkong Thailand', 'kategori_id' => 6, 'satuan' => 'Porsi'],
            ['nama_produk' => 'AIR MINERAL', 'kategori_id' => 7, 'satuan' => 'Botol'],
            ['nama_produk' => 'BEAUTY JUICE', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'ES CENDOL LARAS', 'kategori_id' => 7, 'satuan' => 'Cup'],
            ['nama_produk' => 'HEALTHY JUICE', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JERUK PERAS', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS ALPUKAT', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS BUAH NAGA', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS MANGGA', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS MELON', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS NANAS', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS SEMANGKA', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'jus semangka promo', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS STRAWBERRY', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS TERONG BELANDA', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS TIMUN', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS TOMAT', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'JUS WORTEL', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'MIX JUICE', 'kategori_id' => 7, 'satuan' => 'Gelas'],
            ['nama_produk' => 'basreng', 'kategori_id' => 8, 'satuan' => 'Pack'],
            ['nama_produk' => 'Box Take Away', 'kategori_id' => 8, 'satuan' => 'Pcs'],
            ['nama_produk' => 'Cup Take Away', 'kategori_id' => 8, 'satuan' => 'pcs'],
            ['nama_produk' => 'keripik bawang', 'kategori_id' => 8, 'satuan' => 'Pack'],
            ['nama_produk' => 'kerupuk seblak', 'kategori_id' => 8, 'satuan' => 'Pack'],
            ['nama_produk' => 'Makaroni', 'kategori_id' => 8, 'satuan' => 'Pax'],
            ['nama_produk' => 'oatmeal', 'kategori_id' => 8, 'satuan' => 'Pack'],
            ['nama_produk' => 'Paket Wedding', 'kategori_id' => 8, 'satuan' => 'Paket'],
            ['nama_produk' => 'Lele Bakar', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Cobek', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Goreng', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Kari', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Krispy', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Mangut', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Pokpok', 'kategori_id' => 9, 'satuan' => 'Porsi'],
            ['nama_produk' => '3 pcs otak otak lele', 'kategori_id' => 10, 'satuan' => 'pcs'],
            ['nama_produk' => 'Bakwan Jagung', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Cireng', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'French fries', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Kentang Goreng', 'kategori_id' => 10, 'satuan' => 'Gelas'],
            ['nama_produk' => 'Onion Ring', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Otak Otak Lele', 'kategori_id' => 10, 'satuan' => 'Pieces'],
            ['nama_produk' => 'Tahu Crispy', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Tahu Goreng', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Tempe Mendoan', 'kategori_id' => 10, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Mie Ayam', 'kategori_id' => 11, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Mie Goreng Laras', 'kategori_id' => 11, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Nasi Goreng Laras', 'kategori_id' => 11, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Nasi Pecel', 'kategori_id' => 11, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Nasi Putih', 'kategori_id' => 11, 'satuan' => 'Porsi'],
            ['nama_produk' => 'BANANA MILK', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'CHOCOLATE MILK', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'MATCHA', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'MILKY JELLY BOTOL', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'RED VELVET', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'STRAWBERRY MILK', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'TARO', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'TIRAMISU', 'kategori_id' => 12, 'satuan' => 'Gelas'],
            ['nama_produk' => 'BLUE PARADISE', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'LIME SQUASH', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'LYCHEE MOJITO', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'MANGO SQUASH', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'RED PARADISE', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'SODA GEMBIRA', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'SUMMER PARADISE', 'kategori_id' => 13, 'satuan' => 'Gelas'],
            ['nama_produk' => 'Garden Salad', 'kategori_id' => 14, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Cah Kangkung', 'kategori_id' => 15, 'satuan' => 'Porsi'],
            ['nama_produk' => 'capcay', 'kategori_id' => 15, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Sayur Asem', 'kategori_id' => 15, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Tumis Kailan', 'kategori_id' => 15, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Tumis Pokcoy', 'kategori_id' => 15, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Tumis Toge Ikan Teri', 'kategori_id' => 15, 'satuan' => 'Porsi'],
            ['nama_produk' => 'es batu', 'kategori_id' => 16, 'satuan' => 'Cup'],
            ['nama_produk' => 'Acar', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Kerupuk', 'kategori_id' => 17, 'satuan' => 'Bungkus'],
            ['nama_produk' => 'Kuah Kari', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'kuah mangut', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Sambal Dabu', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Sambal Jeruk', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Sambal Kecap', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Sambal Penyet', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Sambal Terasi', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'telor ceplok', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'telor dadar', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'tempe goreng', 'kategori_id' => 17, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Bakar Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Goreng Rempah Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Kari Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Ayam Mangut Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Bakar Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Cobek Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Goreng Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Kari Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Krispy Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Lele Mangut Tanpa Nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'Soto ayam tanpa nasi', 'kategori_id' => 18, 'satuan' => 'Porsi'],
            ['nama_produk' => 'LEMON SEREH BOTOL', 'kategori_id' => 19, 'satuan' => 'Gelas'],
            ['nama_produk' => 'LEMON TEA', 'kategori_id' => 19, 'satuan' => 'Gelas'],
            ['nama_produk' => 'LYCHEE TEA', 'kategori_id' => 19, 'satuan' => 'Gelas'],
            ['nama_produk' => 'TEH MANIS', 'kategori_id' => 19, 'satuan' => 'Gelas'],
            ['nama_produk' => 'TEH TARIK', 'kategori_id' => 19, 'satuan' => 'Gelas'],
            ['nama_produk' => 'TEH TAWAR', 'kategori_id' => 19, 'satuan' => 'Gelas'],
        ];

        foreach ($menus as $menu) {
            Menu::create($menu);
        }
    }
}
